# Generated by Django 5.0.7 on 2024-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('temperature', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2000, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
