# Generated by Django 5.0.7 on 2024-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(blank=True, default='', max_length=255, null=True),
        ),
    ]
