# Generated by Django 5.0.7 on 2024-08-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Weather', '0002_alter_weather_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(blank=True, default='', max_length=255, null=True),
        ),
    ]
